language: java
jdk:
  - openjdk11

brances:
  only:
    - login   # login 브랜치에 push 가 되었을 때 Travis CI 반응

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build -x test"   # jar 만들기

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp build/libs/*.jar before-deploy/   # jar 파일 넘기기
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축 (폴더 이름은 원하는 이름으로 가능)
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/SpringBoot_Nginx.zip # deploy로 zip파일(원하는 이름으로) 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY         # Travis CI 에서 IAM 사용자 엑세스 키

    secret_access_key: $AWS_SECRET_KEY     # Travis CI 에서 IAM 사용자 비밀 엑세스 키

    bucket: sprint-ci-cd        # S3 Bucket 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private               # zip 파일 공개 여부
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

notification:  # 이메일 알림
  email:
    recipients:
      - sherry0_@kakao.com